// src/components/ui/button.jsx

import * as React from "react";
import { Slot } from "@radix-ui/react-slot"; // Make sure you have @radix-ui/react-slot installed
import { cva } from "class-variance-authority"; // Make sure you have class-variance-authority installed

// Define your button variants (this part is typically generated by Shadcn UI)
const buttonVariants = cva(
  "inline-flex items-center justify-center whitespace-nowrap  text-sm font-medium ring-offset-background transition-colors disabled:pointer-events-none disabled:opacity-50",
  {
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground hover:bg-primary/90",
        destructive:
          "bg-destructive text-destructive-foreground hover:bg-destructive/90",
        outline:
          "border border-input bg-background hover:bg-accent hover:text-accent-foreground",
        secondary:
          "bg-secondary text-secondary-foreground hover:bg-secondary/80",
        ghost: "hover:bg-accent hover:text-accent-foreground",
        link: "text-primary underline-offset-4 hover:underline",
        clear: " cursor-pointer outline-none border-none bg-none p-0 no-underline",
      },
      size: {
        default: "h-10 px-4 py-2",
        sm: "h-9 rounded-md px-3",
        lg: "h-11 rounded-md px-8",
        icon: "h-10 w-10",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
);

// THIS IS THE CRUCIAL PART: Using React.forwardRef
const Button = React.forwardRef(
  ({ className, variant, size, asChild = false, ...props }, ref) => {
    const Comp = asChild ? Slot : "button";
    return (
      <Comp
        className={cva(buttonVariants({ variant, size, className }))()}
        ref={ref} // Pass the ref to the underlying component/element
        {...props}
      />
    );
  }
);
Button.displayName = "Button"; // Good for React DevTools

export { Button, buttonVariants };